use_frameworks!

target 'ALWCategories_Example' do
  pod 'ALWCategories', :path => '../'

  target 'ALWCategories_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
